server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: GMT+8